kind: Deployment
apiVersion: apps/v1
metadata:
  name: amazing-dev
  namespace: amazing-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: amazing-dev
  template:
    metadata:
      labels:
        app: amazing-dev
    spec:
      containers:
        - name: amazing-dev
          image: 751244938937.dkr.ecr.ap-southeast-3.amazonaws.com/amazing:0.0.1
          resources:
            requests:
              memory: "64Mi"
              cpu: "30m"
            limits:
              memory: "4096Mi"
              cpu: "2"
          stdin: true 
          tty: true 
          imagePullPolicy: Always
          ports:
            - containerPort: 80
          livenessProbe:
            httpGet:
              path: /
              port: 80
              # httpHeaders:
            initialDelaySeconds: 3
            periodSeconds: 3
          readinessProbe:
            httpGet:
              path: /
              port: 80
            initialDelaySeconds: 3
            periodSeconds: 3
      restartPolicy: Always
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: amazing-dev-ingress
  namespace: amazing-dev
spec:
  rules:
    - host: amazing-dev.bigboxapp.com
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: amazing-dev-service
                port:
                  number: 80                          
  ingressClassName: nginx
---
kind: Service
apiVersion: v1
metadata:
  name: amazing-dev-service
  namespace: amazing-dev
spec:
  type: NodePort
  ports:
    - name: http
      port: 80
      targetPort: 80
      protocol: TCP
    - name: https
      port: 443
      targetPort: 80
      protocol: TCP      
  selector:
    app: amazing-dev